# Generated by Django 5.1.2 on 2024-10-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_list', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(upload_to='email_attachments/')),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_email', to='emails.list')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=40)),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_list', to='emails.list')),
            ],
        ),
    ]
