# Generated by Django 5.1.2 on 2024-10-23 17:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_email_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
