# Generated by Django 5.1.2 on 2024-10-23 17:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
