# Generated by Django 5.1.2 on 2024-10-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('std_class', models.IntegerField()),
            ],
        ),
    ]
